task: detection

num_classes: 1
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ./dataset/real_colon_dataset_coco_fmt_3subsets_poslesion10_negratio0/train_images/
    ann_file: ./dataset/real_colon_dataset_coco_fmt_3subsets_poslesion10_negratio0/train_ann.json
    transforms:
      type: Compose
      ops: ~
  shuffle: ~
  batch_size: ~
  num_workers: ~
  drop_last: ~

val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ./dataset/real_colon_dataset_coco_fmt_3subsets_poslesion10_negratio0/validation_images/
    ann_file: ./dataset/real_colon_dataset_coco_fmt_3subsets_poslesion10_negratio0/validation_ann.json
    transforms:
      type: Compose
      ops: ~ 
  shuffle: ~
  batch_size: ~
  num_workers: ~
  drop_last: ~

test_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ./dataset/real_colon_dataset_coco_fmt_3subsets_poslesion10_negratio0/test_images/
    ann_file: ./dataset/real_colon_dataset_coco_fmt_3subsets_poslesion10_negratio0/test_ann.json
    transforms:
      type: Compose
      ops: ~ 
  shuffle: ~
  batch_size: ~
  num_workers: ~
  drop_last: ~
