task: detection

num_classes: 1
remap_mscoco_category: True

train_dataloader: 
  type: DataLoader
  dataset: 
    type: RealColonDataset
    img_folder: ./dataset/real_colon_dataset_coco_fmt_3subsets_poslesion-1_negratio1/train_images/
    ann_file: ./dataset/real_colon_dataset_coco_fmt_3subsets_poslesion-1_negratio1/train_ann.json
    neg_ratio: 0.1
    transforms:
      type: Compose
      ops: ~
  shuffle: ~
  batch_size: ~
  num_workers: ~
  drop_last: ~ 

val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ./dataset/real_colon_dataset_coco_fmt_3subsets_poslesion-1_negratio0.1/validation_images/
    ann_file: ./dataset/real_colon_dataset_coco_fmt_3subsets_poslesion-1_negratio0.1/validation_ann.json
    transforms:
      type: Compose
      ops: ~ 
  shuffle: ~
  batch_size: ~
  num_workers: ~
  drop_last: ~

test_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: ./dataset/real_colon_dataset_coco_fmt_3subsets_poslesion-1_negratio1/test_images/
    ann_file: ./dataset/real_colon_dataset_coco_fmt_3subsets_poslesion-1_negratio1/test_ann.json
    transforms:
      type: Compose
      ops: ~
  shuffle: ~
  batch_size: ~
  num_workers: ~
  drop_last: ~
